name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  sast_sonarcloud:
    name: SAST - SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sca_dependencycheck:
    name: SCA - OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: sast_sonarcloud   # ➜ Espera a que termine SAST antes de ejecutarse
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip
          unzip dependency-check-8.4.2-release.zip -d $HOME/depcheck

      - name: Run Dependency Check
        run: |
          $HOME/depcheck/dependency-check/bin/dependency-check.sh \
          --project "DevSecOps Demo" \
          --scan . \
          --format "HTML" \
          --out dependency-report \
          --failOnCVSS 7

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-report
